import Finance from "../Component/Finance/Finance"
import Dashboards from "../Component/Dashboards/Dashboards"
import MyCustomer from "../Component/MyCustomer/MyCustomer"
import Customer from "../Component/Customer/Customer"
import Bank from "../Component/Bank/Bank"
import Home from "../Component/Home/Home"
import {
    UserOutlined,
    FileTextOutlined,
    TeamOutlined,
    HistoryOutlined,
    StarOutlined,
    HomeOutlined,
    AppstoreOutlined,
    BuildOutlined,
    ApartmentOutlined,
    SettingOutlined,
    ContainerOutlined,
    ToolOutlined,
    CreditCardOutlined,
    BankOutlined,
    DollarOutlined,
    FileDoneOutlined,
    IdcardOutlined,
    ClockCircleOutlined,
    SafetyCertificateOutlined,
    ShopOutlined,
    WalletOutlined,
    BuildTwoTone,
} from "@ant-design/icons"
import Floor from "../Component/Floor/Floor"

const publicRoutes = [
    {key: "customer-management", label: "Khách hàng & hợp đồng", icon: <UserOutlined />},
    {
        key: "/customers",
        path: "/customers",
        label: "Khách hàng",
        parent: "customer-management",
        component: Customer,
        icon: <UserOutlined />,
    },
    {
        key: "/contracts",
        path: "/contracts",
        label: "Hợp đồng thuê",
        parent: "customer-management",
        component: Dashboards,
        icon: <FileTextOutlined />,
    },
    {
        key: "/room-mates",
        path: "/room-mates",
        label: "Bạn cùng phòng",
        parent: "customer-management",
        component: Dashboards,
        icon: <TeamOutlined />,
    },
    {
        key: "/customer-history",
        path: "/customer-history",
        label: "Lịch sử khách hàng",
        parent: "customer-management",
        component: Dashboards,
        icon: <HistoryOutlined />,
    },
    {
        key: "/customer-rating",
        path: "/customer-rating",
        label: "Xếp hạng & đánh giá",
        parent: "customer-management",
        component: Dashboards,
        icon: <StarOutlined />,
    },
    {key: "building-management", label: "Tòa nhà & phòng", icon: <HomeOutlined />},
    {
        key: "/homes",
        path: "/homes",
        label: "Danh sách nhà",
        parent: "building-management",
        component: Home,
        icon: <ShopOutlined />,
    },
    {
        key: "/floors",
        path: "/floors",
        label: "Tầng",
        parent: "building-management",
        component: Floor,
        icon: <ApartmentOutlined />,
    },
    {
        key: "/rooms",
        path: "/rooms",
        label: "Phòng",
        parent: "building-management",
        component: Dashboards,
        icon: <AppstoreOutlined />,
    },
    {
        key: "/room-layout",
        path: "/room-layout",
        label: "Bố trí phòng",
        parent: "building-management",
        component: Dashboards,
        icon: <BuildOutlined />,
    },
    {
        key: "/room-history",
        path: "/room-history",
        label: "Lịch sử sử dụng",
        parent: "building-management",
        component: Dashboards,
        icon: <HistoryOutlined />,
    },
    {
        key: "/smart-home",
        path: "/smart-home",
        label: "Smart Home",
        parent: "building-management",
        component: Dashboards,
        icon: <SettingOutlined />,
    },
    {key: "asset-management", label: "Tài sản & nội thất", icon: <ContainerOutlined />},
    {
        key: "/products",
        path: "/products",
        label: "Danh mục sản phẩm",
        parent: "asset-management",
        component: Dashboards,
        icon: <ContainerOutlined />,
    },
    {
        key: "/assets",
        path: "/assets",
        label: "Tài sản phòng",
        parent: "asset-management",
        component: Dashboards,
        icon: <AppstoreOutlined />,
    },
    {
        key: "/asset-maintenance",
        path: "/asset-maintenance",
        label: "Lịch sử bảo trì",
        parent: "asset-management",
        component: Dashboards,
        icon: <ToolOutlined />,
    },
    {key: "payment-management", label: "Thanh toán & công nợ", icon: <WalletOutlined />},
    {
        key: "/payment-schedule",
        path: "/payment-schedule",
        label: "Lịch thanh toán",
        parent: "payment-management",
        component: Dashboards,
        icon: <CreditCardOutlined />,
    },
    {
        key: "/debt-management",
        path: "/debt-management",
        label: "Công nợ khách hàng",
        parent: "payment-management",
        component: Dashboards,
    },
]

export {publicRoutes}
